language: python
python:
  - "3.5"

# The build script is still under development.
script:
  - python build.py
  
# Notifications after completion of the build.
notifications:
   email: 
     - jallib@googlegroups.com
